# Generated by Django 3.0.1 on 2020-02-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterView',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('interviewer', models.IntegerField()),
                ('schedule_timestamp', models.DateField()),
                ('result', models.CharField(max_length=20)),
                ('applicant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicant.Applicant')),
            ],
        ),
    ]
