# Generated by Django 3.0.1 on 2020-02-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Emp_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=12, unique=True)),
                ('Designation', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
