# Generated by Django 3.0.1 on 2020-02-27 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0002_auto_20200227_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitPost',
            fields=[
                ('oppcode', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('qualification', models.CharField(max_length=30)),
                ('start_register', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('last_register', models.CharField(max_length=30)),
                ('dept_id', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=250)),
                ('cno', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='InterModel',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('schedule', models.DateField()),
                ('app_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicant.Applicant')),
            ],
        ),
    ]
