# Generated by Django 3.0.1 on 2020-02-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitpost',
            name='last_register',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='recruitpost',
            name='start_register',
            field=models.DateField(max_length=30),
        ),
    ]
