# Generated by Django 3.0.1 on 2020-05-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0002_auto_20200228_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitpost',
            name='last_register',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recruitpost',
            name='start_register',
            field=models.DateField(),
        ),
    ]
