# Generated by Django 3.0.1 on 2020-02-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('gender', models.CharField(max_length=30)),
                ('m_no', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('percentage', models.IntegerField()),
                ('resume', models.FileField(upload_to='document/')),
            ],
        ),
    ]
